# yaml-language-server: $schema=../../../../charts/cilium/values.schema.json

cluster:
  name: main
  id: 2

k8sClientRateLimit:
  qps: 10
  burst: 20

ingressController:
  enabled: true
  loadbalancerMode: shared
  defaultSecretNamespace: "external-certs"
  defaultSecretName: "cluster-ingress"

bpf:
  preallocateMaps: true
  distributedLRU:
    enabled: true
  # https://docs.cilium.io/en/stable/operations/performance/tuning/#ebpf-map-backend-memory
  mapDynamicSizeRatio: 0.08
