# yaml-language-server: $schema=../../../../charts/cilium/values.schema.json

cluster:
  name: robot
  id: 3

k8sClientRateLimit:
  qps: 10
  burst: 20

ipv4NativeRoutingCIDR: 10.137.0.0/16
ipv6NativeRoutingCIDR: fc42:0:0:89::/64

operator:
  replicas: 1
