# yaml-language-server: $schema=../../../../charts/tcpm/values.schema.json

image:
  # https://hub.docker.com/r/rdavidoff/twitch-channel-points-miner-v2
  repository: rdavidoff/twitch-channel-points-miner-v2
  tag: "2.0.3"

podAnnotations:
  reloader.stakater.com/auto: "true"

configMaps:
  config:
    enabled: false

persistence:
  config:
    enabled: true
    name: twitch-config
  cookie:
    enabled: true
    name: twitch-cookie
